language: c
before_install:
  - sudo apt-get update
  - wget http://static.rust-lang.org/dist/rust-nightly-x86_64-unknown-linux-gnu.tar.gz -O /tmp/rust-nightly-x86_64-unknown-linux-gnu.tar.gz
install:
  - tar -C /tmp -zxvf /tmp/rust-nightly-x86_64-unknown-linux-gnu.tar.gz
  - sudo /tmp/rust-nightly-x86_64-unknown-linux-gnu/install.sh
  - sudo apt-get install libfuse-dev
script:
  - make all
  - make check
  - make examples
