language: rust
env:
  global:
    - secure: GMDU5g5cG1LmlhcXUmDwEV57oNYWOqi8YXswhP7oMdZkC+Nf/Bw0UX18dNlJ9zaqoKKJ07wIVdKO5Jy5VLtybt+/f8NF1OgOKgx6sYAPDEHc4jZtqEj16bxfRXuzOUtTut3nuf41ZJhNgj4+W8qDSkFEWuhp7EJ3DcXHnXl9/3A=
before_install:
  - sudo apt-get update
install:
  - sudo apt-get install libfuse-dev
script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo doc --verbose
after_success: |
  mv target/doc . &&
  (curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh)
