language: rust
env:
  global:
    - secure: atCJyliV0MQp8aNBrDc1iymeAxNJWFZPU0OmyhK94+/1FjU1pw7MU3cdSCN1dHY82/4bmKGsewRwCnpj5SPYPG2BbOSAuKobLvGO/mlagqFrdnJtmCmsGda0F2wZ3PNC30zfx0L+TsngB34URcgWGCfzPvyDS0JuHTIwl25YiX8=
before_install:
  - sudo apt-get update
install:
  - sudo apt-get install libfuse-dev
script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo doc --verbose
after_success: |
  [ $TRAVIS_BRANCH = master ] &&
  mv target/doc . &&
  (curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh)
