[project]
name = "fuse"
version = "0.2.0"
authors = ["Andreas Neuhaus <zargony@zargony.com>"]

[lib]
name = "fuse"
path = "src/lib.rs"

[[bin]]
name = "hello"
path = "examples/hello.rs"
test = false
doc = false

[[bin]]
name = "null"
path = "examples/null.rs"
test = false
doc = false
