[package]
name = "fuse"
version = "0.2.0"
authors = ["Andreas Neuhaus <zargony@zargony.com>"]
description = "Rust library for filesystems in userspace (FUSE)"
homepage = "https://github.com/zargony/rust-fuse"
repository = "https://github.com/zargony/rust-fuse"
readme = "README.md"
keywords = ["fuse", "filesystem", "system", "bindings"]
license = "MIT"

[dependencies]
time = "*"

[lib]
name = "fuse"
path = "src/lib.rs"

[[bin]]
name = "hello"
path = "examples/hello.rs"
test = false
doc = false

[[bin]]
name = "null"
path = "examples/null.rs"
test = false
doc = false
